FROM node:22-alpine
WORKDIR /app
COPY package.json .
COPY apps/web/package.json apps/web/package.json
COPY packages/webrtc-client/package.json packages/webrtc-client/package.json
COPY packages/shared-types/package.json packages/shared-types/package.json
RUN npm install
COPY . .
CMD ["npm", "--workspace", "apps/web", "run", "dev"]
