FROM node:22-alpine
WORKDIR /app
COPY package.json .
COPY apps/signaling/package.json apps/signaling/package.json
COPY packages/shared-types/package.json packages/shared-types/package.json
RUN npm install
COPY . .
CMD ["npm", "--workspace", "apps/signaling", "run", "dev"]
