FROM node:22-alpine
WORKDIR /app
COPY package.json .
COPY apps/gateway/package.json apps/gateway/package.json
COPY packages/shared-types/package.json packages/shared-types/package.json
RUN npm install
COPY . .
CMD ["npm", "--workspace", "apps/gateway", "run", "dev"]
